"battlepass_treasures"
{
	"treasure_hallowed_shimmer"
	{
		"Rarity"		"rare"
		"Source"
		{
			"Coins"		"750"
		}
	}
	"treasure_winter"
	{
		"Rarity"		"rare"
		"Source"
		{
			"Coins"		"750"
		}
	}
	"treasure_pathfinders_gift"
	{
		"Rarity"		"mythical"
		"Source"
		{
			"Coins"		"1000"
		}
	}
	"treasure_pathfinders_treasure"
	{
		"Rarity"		"legendary"
		"Source"
		{
			"Coins"		"1250"
		}
	}
	"treasure_pathfinders_trophy"
	{
		"Rarity"		"arcana"
		"Source"
		{
			"Coins"		"1500"
		}
	}
}
